---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: fastapi
  name: fastapi-placement
  namespace: fastapi
spec:
  clusterSelector:
    matchExpressions:
      - key: purpose
        operator: In
        values:
          - development
          - production
