apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- route.yaml
- service.yaml

patches:
- target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: fastapi-route
    namespace: fastapi
  patch: |-
    - op: replace
      path: /spec/host
      value: "f.apps.lagomes.rhbr-lab.com"
