apiVersion: v1                    
kind: Namespace
metadata:
  name: fastapi                             
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: fastapi
  namespace: fastapi
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - fastapi
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-laurobmb-fastap-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-laurobmb-fastap
  namespace: ggithubcom-laurobmb-fastap-ns
spec:
  type: Git
  pathname: 'https://github.com/laurobmb/fastapi.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: k8s/
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: fastapi
  name: fastapi-subscription-1
  namespace: fastapi
spec:
  channel: ggithubcom-laurobmb-fastap-ns/ggithubcom-laurobmb-fastap
  placement:
    placementRef:
      kind: PlacementRule
      name: fastapi-placement-1
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: fastapi
  name: fastapi-placement-1
  namespace: fastapi
spec:
  clusterSelector:
    matchLabels:
      'purpose': 'production'
      'purpose': 'development'
