---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: fastapi-25gxs-prod
  name: fastapi-25gxs-prod-placement
  namespace: fastapi-prod
spec:
  clusterSelector:
    matchExpressions:
      - key: purpose
        operator: In
        values:
          - development
          - production
