---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: k8s/overlays/25gxs-dev
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: fastapi
  name: fastapi-subscription
  namespace: fastapi
spec:
  channel: fastapi-channel-ns/fastapi-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: fastapi-placement
