---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namePrefix: dev-

namespace: fastapi-dev

commonLabels:
  env: fastapi-dev

patches:
- target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: fastapi-route
  patch: |-
    - op: replace
      path: /spec/host
      value: "fastapi-dev.apps.lagomes.rhbr-lab.com"

- target:
    version: v1
    group: apps
    kind: Deployment
    name: fastapi-deployment
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

- target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: fastapi-route
  patch: |-
    - op: replace
      path: /spec/to/name
      value: "dev-fastapi-service"

- target:
    version: v1
    group: apps
    kind: Service
    name: fastapi
  patch: |-
    - op: replace
      path: /metadata/name
      value: "fastapi-dev"

- target:
    version: v1
    group: apps
    kind: Deployment
    name: fastapi-deployment
  patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ENVIROMENT
        value: "dev"
