---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
- target:
    version: v1
    group: route.openshift.io
    kind: Route
    name: fastapi-route
    namespace: fastapi
  patch: |-
    - op: replace
      path: /spec/host
      value: "fastapi-dev.apps.lagomes.rhbr-lab.com"
