---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  namespace: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      namespace: fastapi
    spec:
      containers:
      - name: fastapi
        image: quay.io/laurobmb/fastapi:latest
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 8000
