---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
      namespace: fastapi
    spec:
      containers:
      - name: fastapi
        image: quay.io/lagomes/fastapi:latest
        imagePullPolicy: Always
        env:
        - name: ENVIROMENT_INFO
          value: "beta"
        ports:
        - name: http-port
          containerPort: 8000
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 128Mi
        volumeMounts:
        - name: password
          mountPath: /opt/secrets
        - name: config
          mountPath: /opt/config
      volumes:
      - name: password
        secret:
          secretName: fastapi-secret
      - name: config
        configMap:
          name: fastapi-cm
