apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: fastapi
  name: fastapi-route
spec:
  #host: "PATCH_ME"
  host: ""
  wildcardPolicy: None
  port:
    targetPort: 8080
  to:
    kind: Service
    name: fastapi-service
    weight: 100
